### PR TITLE
#105: add setting to show scores instead of percentage in poll summary

### PR DESCRIPTION
**Pull request by Axelfoley85**
#### Locally tested
- score summary looks fine
- settings can be switched to show percentage or not
- sqlite database looks fine, correct column gets switched, when setting checkbox

### CODE REVIEW

**Comment by Axelfoley85** [comment]
Somebody review please. Cant add anybody in the review section. Probably since not part of the project. @Akasch @hprid @miterion @femtobit

**Review by wichmannpas — APPROVED** [review]
Thanks for your PR! Looks good to me.
On a side note, it would be nice if we could have updated translations for the new strings.

**Comment by Axelfoley85** [comment]
Hi @wichmannpas . Thanks so much for the response. I have added now translation for the new strings. Unfortunately I wasn't able to review the translation. When I click on "Deutsch"  locally the translation is quite incomplete. This also happens for me on a clean master branch.

What is the usual procedure for the translation adaptations? When I run `./manage.py makemessages` I get quite a lot of changes that don't seem all to be related to my changes.

**Comment by Axelfoley85** [comment]
@wichmannpas Any chance moving along with this PR?

**Pull request merged**
