### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by loviuz**
Hi,

I have added full italian translation in po file and I have added the link in the footer to change language to italian.
I have seen that there are some strings that are not translated like "yes", "no", "maybe", etc... Can I try to make them translatable?

Thanks for this wonderful project :-)

### CODE REVIEW

**Comment by ftsell** [comment]
Thanks for the contribution, it is very welcome :)

Based on your profile I assume you are a native speaker and either didn't do it via ChatGPT or at least verified the translations?

> I have seen that there are some strings that are not translated like "yes", "no", "maybe", etc... Can I try to make them translatable?

I saw that you already added the translation keys but only translated them in italian so yeah go ahead if you want to.
Small heads-up though: Editing existing .po files sometimes creates very large diffs depending on the editor you use because they sort the keys or update some metadata of every key. This will make it more difficult to review so you might want to open a separate PR for that just to make things easier.

**Comment by loviuz** [comment]
> Based on your profile I assume you are a native speaker and either didn't do it via ChatGPT or at least verified the translations?

Yes, I confirm I am italian, I am not a bot and I have translated manually, by checking the application after the translation.

> I saw that you already added the translation keys but only translated them in italian so yeah go ahead if you want to.
Small heads-up though: Editing existing .po files sometimes creates very large diffs depending on the editor you use because they sort the keys or update some metadata of every key. This will make it more difficult to review so you might want to open a separate PR for that just to make things easier.

The translated .po file were missing, I have added it from scratch. Do I have to do something else to the PR or this is an advice for the next PR?

**Comment by ftsell** [comment]
> Yes, I confirm I am italian, I am not a bot and I have translated manually, by checking the application after the translation.

Very nice :)

> > I saw that you already added the translation keys but only translated them in italian so yeah go ahead if you want to.
> > Small heads-up though: Editing existing .po files sometimes creates very large diffs depending on the editor you use because they sort the keys or update some metadata of every key. This will make it more difficult to review so you might want to open a separate PR for that just to make things easier.
> 
> The translated .po file were missing, I have added it from scratch. Do I have to do something else to the PR or this is an advice for the next PR?

For this PR you did everything correctly.
What I meant is that you did not just add a translation for italian but also introduced new translation keys (e.g. `yes`, `no`, ...). It is totally fine to do so but I wanted to give you a heads up in case you were thinking about adding these to the english or german `.po` files.

---

@timonegk or @Akasch Do you want to add anything? Because otherwise I would like to approve and merge this PR.

**Comment by loviuz** [comment]
> What I meant is that you did not just add a translation for italian but also introduced new translation keys (e.g. yes, no, ...). It is totally fine to do so but I wanted to give you a heads up in case you were thinking about adding these to the english or german .po files.

It's all clear. In the next PRs I will keep additions more separated ;-)

**Review by timonegk — APPROVED** [review]
I approve, thanks a lot!

**Review by ftsell — APPROVED** [review]

**Pull request merged**
