### PR TITLE
Add Dockerfile

### LINKED ISSUE #67: Provide Dockerfile
It would be cool to have this project enabled for Docker deployments.

### PR DESCRIPTION
**Pull request by Akasch**
This pull requests adds a multistage Dockerfile to be used with an external Database, and a Webserver serving static assets. Both uwsgi and http ports are exposed for convenience if not using with nginx.

At the moment the raw assets (JS and CSS) files are included in the final build, but this can be improved later

Fixes #67

### CODE REVIEW

**Review by timonegk — COMMENTED** [review]
Works nicely. I am not so sure about the Dockerfile itself as it seems rather hacky, especially the `/install` part. I'm also not sure why the final container even works without the apt packages installed.
Also maybe add the `run` folder to `.gitignore`.

**Comment by Akasch** [comment]
The apt packages are either Packet-managers (pip, npm) or build time dependencys for python code installed with pip. Both is not needed for running the python code.
The only think i haven't tested and i am unsure about is the ldap libs, it could be that some of them are required.

The /install folder is used to make the it more easy to copy the compiled end extracted python packages to /usr/local without making a copy in the Docker-Layers of the other data in /usr/local

I want to replace the copy step in the collectstatic stage with links or environment Variables but have to research how to do it exactly. But as this layer is not build into the final image the wasted space is not that big of a deal.

**Review by wichmannpas — APPROVED** [review]
Looks fair enough, several not so clean spots.

**Comment by paroga** [comment]
I have another `Dockerfile` at https://github.com/foodcoopsat/bitpoll/blob/main/Dockerfile. It would be great if you could add MySQL/MariaDB support too and do not use `sentry.mafiasi.de`, so it's possible to reuse the built image.
Adding support for serving static files in the default configuration would be great too. A reverse proxy in front of the container could route request for static files to e.g. a nginx container anyway.

**Comment by Akasch** [comment]
I have the feeling we use some functions not compatible with MySQL, i have too look into that, most likely in the invention and/or group code.

For senty.mafiasi.de there should only be not active example config for it in the repo but I will have a look.

For the reverse Porxy: We could add an example nginx file. I think the way to do it in the docker world would be a docker compose file.

**Pull request merged**
